# Generated by Django 4.2.20 on 2025-10-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='password_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PASTOR', 'Pastor'), ('HELPER', 'Helper')], default='PASTOR', max_length=10),
        ),
    ]
