# Generated by Django 4.2.20 on 2025-10-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customeruser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
