# Generated by Django 4.2.20 on 2025-10-11 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customeruser_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruser',
            old_name='password_changes',
            new_name='password_changed',
        ),
    ]
