# Generated by Django 4.2.20 on 2025-11-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customeruser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PASTOR', 'Pastor'), ('HELPER', 'Helper'), ('CAMPAIGN_MANAGER', 'Campaign Manager')], default='PASTOR', max_length=20),
        ),
    ]
