# Generated by Django 4.2.20 on 2025-11-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customeruser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
