# Generated by Django 4.2.20 on 2025-10-11 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0005_alter_customeruser_username'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique key (used in submission data).', max_length=100)),
                ('label', models.CharField(help_text='The field label shown on the form.', max_length=150)),
                ('field_type', models.CharField(choices=[('text', 'Text Field'), ('textarea', 'Text Area'), ('number', 'Number'), ('select', 'Select Dropdown'), ('image', 'Image Upload'), ('file', 'File Upload'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date & Time'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('email', 'Email')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, help_text='For select fields, provide a list of options.', null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_period', models.DateField(help_text='The first day of the month this submission is for.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-submission_period', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SubmissionFieldFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='campaign_submissions/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_files', to='campaigns.campaignfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='campaigns.submission')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='submission',
            name='pastor',
            field=models.ForeignKey(limit_choices_to={'role': 'pastor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.service'),
        ),
        migrations.AddField(
            model_name='campaignfield',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='campaigns.campaign'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('pastor', 'campaign', 'submission_period')},
        ),
        migrations.AlterUniqueTogether(
            name='campaignfield',
            unique_together={('campaign', 'name')},
        ),
    ]
