# Generated by Django 4.2.20 on 2025-11-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_antibrutishcampaign_antibrutishsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basontaproliferationsubmission',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intimatecounselingsubmission',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheperdingcontrolsubmission',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sundaymanagementsubmission',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swollensundaysubmission',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technologysubmission',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
