# Generated by Django 4.2.20 on 2025-11-09 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0004_add_date_field_to_submissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'CAMPAIGN_MANAGER'}, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Manager Assignment',
                'verbose_name_plural': 'Campaign Manager Assignments',
                'db_table': 'campaign_manager_assignments',
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
