# Generated by Django 4.2.20 on 2025-11-10 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0005_campaignmanagerassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmanagerassignment',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'CAMPAIGN_MANAGER'}, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
