# Generated by Django 4.2.20 on 2025-11-10 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customeruser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0006_alter_campaignmanagerassignment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons')),
                ('campaign_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='Active', max_length=20)),
            ],
            options={
                'db_table': 'campaign_equip',
            },
        ),
        migrations.CreateModel(
            name='EquipmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_period', models.DateField(blank=True, help_text='The first day of the month this submission is for.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('equipment_name', models.CharField(blank=True, max_length=200, null=True)),
                ('equipment_type', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, help_text='e.g., New, Good, Fair, Poor', max_length=100, null=True)),
                ('location', models.CharField(blank=True, help_text='Where the equipment is located', max_length=200, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True)),
                ('warranty_expiry_date', models.DateField(blank=True, null=True)),
                ('maintenance_notes', models.TextField(blank=True, null=True)),
                ('is_functional', models.BooleanField(blank=True, default=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='campaigns.equipmentcampaign')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.service')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submission_equip',
            },
        ),
        migrations.CreateModel(
            name='EquipmentSubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='campaign_submissions/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='campaigns.equipmentsubmission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
